### ISSUE TITLE
Release build fails

### ISSUE THREAD

**Issue by adarshbalu** [adarshbalu/elderly_app#2]
Release build of the application fails for some reason.

**Comment by shatanikmahanty** [comment]
Hi, I downloaded your code to my machine. I upgraded all dependencies and tried building release apk and it generated successfully. let me know if need the updated source

**Comment by adarshbalu** [comment]
> Hi, I downloaded your code to my machine. I upgraded all dependencies and tried building release apk and it generated successfully. let me know if need the updated source

Send a pull request with all the changes.

**Comment by shatanikmahanty** [comment]
Ok

**Comment by shatanikmahanty** [comment]
I am getting this message if I create a pull request : 
Can't create pull request
Push failed: remote: Permission to adarshbalu/elderly_app.git denied to shatanikmahanty. unable to access 'https://github.com/adarshbalu/elderly_app.git/': The requested URL returned error: 403

**Comment by adarshbalu** [comment]
> I am getting this message if I create a pull request :
> Can't create pull request
> Push failed: remote: Permission to adarshbalu/elderly_app.git denied to shatanikmahanty. unable to access 'https://github.com/adarshbalu/elderly_app.git/': The requested URL returned error: 403

You are trying to push the code to the repository.
First fork the repo and then add your changes. Then push those changes. Later come to the pull requests and add one from there.

**Comment by shatanikmahanty** [comment]
Ok Thanks will do that

**Comment by shatanikmahanty** [comment]
I followed your suggested process and was able to create pull request 👍

**Comment by adarshbalu** [comment]
> I followed your suggested process and was able to create pull request 👍

Cool! Your changes are merged.
