### ISSUE TITLE
information

### ISSUE THREAD

**Issue by nlictic** [adarshbalu/elderly_app#4]
I would like to insert the Arduino system into your. Do you have any suggestions?
my email cisse9.tc@gmail.com

**Comment by adarshbalu** [comment]
> I would like to insert the Arduino system into your. Do you have any suggestions?
> my email [cisse9.tc@gmail.com](mailto:cisse9.tc@gmail.com)

Fork the repository and carry on with any idea that you have.

**Comment by nlictic** [comment]
Do you have the java version of your Elderly Companion Application project

**Comment by adarshbalu** [comment]
> Do you have the java version of your Elderly Companion Application project

No, It's a Flutter project

**Comment by nlictic** [comment]
Thank you so much,
I am new to programming in Android java, I wanted to use your project to increase my knowledge

**Comment by adarshbalu** [comment]
> Thank you so much,
> I am new to programming in Android java, I wanted to use your project to increase my knowledge

This project is not Android Java. It's Flutter project. As it's open source you may use it for your learning purpose. Good luck.
